### ISSUE TITLE
直接用action不更省事吗

### ISSUE THREAD

**Issue by xiyaowong** [fslongjin/This-repo-has-357-stars#11]
你这应该是用webhook吧？为啥不用action，这样更方便，省去自己的服务

**Comment by Dragon1573** [comment]
> 为啥不用Action？

因为这种场景下没法使用 Actions 。

在 GitHub Codespace 功能正式发布之前，有一个仓库可以把 GitHub Actions 中自动创建的测试实例暴露给用户，供用户以 ECS 的形式白嫖 GitHub 服务器。后来随着 GitHub Codespace 上线，这个仓库失去了它的价值，同时也因为违反 GitHub 最终用户协议而被警告。

项目有提及 GitHub Actions 创建的测试实例最多只会连续运行6小时，超过6小时会被强制释放且任务标记为失败（超时）。

以 Python 版本源码为例，主逻辑使用了 `while True` 和 `sleep(3)` 的形式，借助死循环配合线程休眠来实现“定时刷新”。死循环必然会导致程序无法自动退出，6小时后容器被杀定时任务也会随之失效。

其次，即使更改源代码逻辑，直接借助 Actions 自身的定时任务也不可行。Actions 要求 Scheduler Workflows 的最短触发周期为5分钟，这样肯定无法跟上 Stars 的刷新频率。

所以，最好的方式是使用自有的设备，直接运行脚本并死循环长时间周期性调 WebHooks 实现定时更新，或者配置高频（比如3～5秒触发一次） Crontab 定时任务实现更新。
